services:
  php:
    container_name: setup-symfony-php
    build:
      context: ./.docker/php
      dockerfile: Dockerfile
    # restart: unless-stopped
    # tty: true
    volumes:
      - ./:/var/www
      - ./.docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - setup-symfony-network
    depends_on:
      - db

  nginx:
    container_name: setup-symfony-nginx
    build:
      context: ./.docker/nginx
      dockerfile: Dockerfile
    # restart: unless-stopped
    # tty: true
    ports:
      - '8080:80'
      - '443:443'
    volumes:
      - ./:/var/www
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - setup-symfony-network
    depends_on:
      - php

  db:
    container_name: setup-symfony-db
    image: postgres:16.3
    # restart: always
    # tty: true
    volumes:
      - setup-symfony-data:/var/lib/postgresql/data
    networks:
      - setup-symfony-network
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}

networks:
  setup-symfony-network:
    driver: bridge

volumes:
  setup-symfony-data:
    driver: local